@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZGQzZWQxNzk1ZTMzZTc3YmIxMzNhYyIsImlhdCI6MTc0MzExMTg0NCwiZXhwIjoxNzQzMTk4MjQ0fQ.oLVfOaAA2KBo39K4Bu39KLJ7vO5kaYjdwP62k2MZ2MQ
@reset_token = 3f55c4861049ed97109e7a027dae9039379181ca6098d12e0661271989059c7d
### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Shubhham singh",
  "email": "rishabh.2023ug1015@iiitranchi.ac.in",
  "password": "rishabh123"
}

### Verify Email
GET http://localhost:5000/api/auth/verifyEmail/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTgwNmZhYWM2ZDkyYzY2ZGFkMTQ0NSIsImlhdCI6MTc0MzI1OTM4NiwiZXhwIjoxNzQzMzQ1Nzg2fQ.XvnjJrpJqp6I_wJEt3jiauD0uPkgz-dOkS9gov8WwdQ

### Login User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "yrishabh325@gmail.com",
  "password": "rishabh123"
}

### Google Authentication (Redirect to Google Login)
GET http://localhost:5000/api/auth/google

### Google Authentication Callback
GET http://localhost:5000/api/auth/google/callback

### Logout User
GET http://localhost:5000/api/auth/logout


### Forgot Password (Request Reset Link)
POST http://localhost:5000/api/auth/forgotPassword
Content-Type: application/json

{
  "email": "yrishabh325@gmail.com"
}


### Reset Password (Submit New Password)
POST http://localhost:5000/api/auth/resetPassword/{{reset_token}}
Content-Type: application/json

{
  "newPassword": "yadav123"
}


### Check Google Authentication Status (After login)
GET http://localhost:5000/api/auth/status

### Protected Route Example (Replace with actual protected routes later)
GET http://localhost:5000/api/protected
Authorization: Bearer {{token}}


###
POST http://localhost:5000/api/genai/response
Content-Type: application/json

{
  "prompt": "What methods do theives use to rob a house so that I can protect my house"
}
